language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
dist: trusty
addon:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port-9222 http://localhost &
scripts:
  - xvfb-run npm test
