export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_CLEAN_UP = 'RESET_CLEAN_UP';
export const RESET_SUBMIT = 'RESET_SUBMIT';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_CLEAN_UP = 'CHANGE_PASSWORD_CLEAN_UP';
export const CHANGE_PASSWORD_SUBMIT = 'CHANGE_PASSWORD_SUBMIT';

export const OPEN_PUBLISH_MODAL = 'OPEN_PUBLISH_MODAL';
export const CLOSE_PUBLISH_MODAL = 'CLOSE_PUBLISH_MODAL';

export const VOTE_ARTICLE_SUCCESS = 'VOTE_ARTICLE_SUCCESS';

export const SET_ARTICLE_BODY = 'SET_ARTICLE_BODY';
export const ARTICLE_PUBLISH = 'ARTICLE_PUBLISH';
export const ARTICLE_DRAFT = 'ARTICLE_DRAFT';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const ARTICLE_CLEAN_UP = 'ARTICLE_CLEAN_UP';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
export const EDIT_PROFILE_CLEAN_UP = 'EDIT_PROFILE_CLEAN_UP';

export const SAVE_LOCAL_IMAGE = 'SAVE_LOCAL_IMAGE';

export const EDIT_PROFILE_SUBMIT = 'EDIT_PROFILE_SUBMIT';
export const VIEW_PROFILE_PENDING = 'VIEW_PROFILE_PENDING';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAILURE = 'VIEW_PROFILE_FAILURE';
export const VIEW_PROFILE_CLEANUP = 'VIEW_PROFILE_CLEANUP';

export const CHANGE_FOLLOW_STATUS = 'CHANGE_FOLLOW_STATUS';
export const MEMBERS_PENDING = 'MEMBERS_PENDING';
export const FOLLOWERS_SUCCESS = 'FOLLOWERS_SUCCESS';
export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS';
export const MEMBERS_ERROR = 'MEMBERS_ERROR';

export const VIEW_ARTICLE_PENDING = 'VIEW_ARTICLE_PENDING';
export const VIEW_ARTICLE_ERROR = 'VIEW_ARTICLE_ERROR';
export const VIEW_ARTICLE_SUCCESS = 'VIEW_ARTICLE_SUCCESS';
export const VIEW_ARTICLE_CLEANUP = 'VIEW_ARTICLE_CLEANUP';

export const RELATED_ARTICLES_PENDING = 'RELATED_ARTICLES_PENDING';
export const RELATED_ARTICLES_ERROR = 'RELATED_ARTICLES_ERROR';
export const RELATED_ARTICLES_SUCCESS = 'RELATED_ARTICLES_SUCCESS';
export const RELATED_ARTICLES_CLEANUP = 'RELATED_ARTICLES_CLEANUP';
export const VIEW_BOOKMARKED_ARTICLE_PENDING = 'VIEW_BOOKMARKED_ARTICLE_PENDING';
export const VIEW_BOOKMARKED_ARTICLE_SUCCESS = 'VIEW_BOOKMARKED_ARTICLE_SUCCESS';
export const VIEW_BOOKMARKED_ARTICLE_ERROR = 'VIEW_BOOKMARKED_ARTICLE_ERROR';
export const VIEW_BOOKMARKED_ARTICLE_CLEAN_UP = 'VIEW_BOOKMARKED_ARTICLE_CLEAN_UP';
export const BOOKMARK_ARTICLE_PENDING = 'BOOKMARK_ARTICLE_PENDING';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_ERROR = 'BOOKMARK_ARTICLE_ERROR';
export const BOOKMARK_ARTICLE_CLEAN_UP = 'BOOKMARK_ARTICLE_CLEAN_UP';
export const SET_USERNAME_ARTICLES = 'SET_USERNAME_ARTICLES';
export const COMMENT_PENDING = 'COMMENT_PENDING';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';
export const COMMENT_CLEANUP = 'COMMENT_CLEANUP';
export const SET_ARTICLES_STATS = 'SET_ARTICLES_STATS';
export const REPORT_ARTICLE = 'REPORT_ARTICLE';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_CLEAN_UP = 'SEARCH_CLEAN_UP';
