export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_CLEAN_UP = 'RESET_CLEAN_UP';
export const RESET_SUBMIT = 'RESET_SUBMIT';
export const OPEN_PUBLISH_MODAL = 'OPEN_PUBLISH_MODAL';
export const CLOSE_PUBLISH_MODAL = 'CLOSE_PUBLISH_MODAL';
export const SET_ARTICLE_BODY = 'SET_ARTICLE_BODY';
export const SET_ARTICLE_TAG = 'SET_ARTICLE_TAG';
